### ISSUE TITLE
Install issues Arch

### ISSUE THREAD

**Issue by daedaevibin** [me-js-bro/hyprconf-install#17]
Doesn't work for minimal install. Fails to install and enable sddm, and even after doing so by hand it doesn't load in.

I'm not sure what's missing, so I don't know what to install and setup by hand to get the system working

**Comment by me-js-bro** [comment]
I will be check and fix it very soon. thanks a lot.

**Comment by me-js-bro** [comment]
I think this issue is causing the gpu drivers. I'm not sure. I have no gpu in my pc, that's why I am totally unable to check and fix the bug. I would be appreciate if anyone fixes the issue who has a gpu in his pc. thanks a lot.
